# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190111_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/m', verbose_name='头像'),
        ),
    ]
